apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
spec:
  type: NodePort
  ports:
  - name: "result-service"
    port: 8081
    targetPort: 80
    nodePort: 31001
  selector:
    app: result

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: result
  labels:
    name: result
spec:
  ingressClassName: nginx
  rules:
  - host: result.dwyor.xyz
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: result
            port:
              number: 8081